import type { Prisma } from "@prisma/client";

/**
 * Catálogo inicial de planos. É CONFIGURAÇÃO (não dado fictício): criado uma única vez pelo seed/bootstrap
 * e depois editado pelo SUPER_ADMIN em /admin/plans. A interface lê preços e limites sempre do banco.
 */
export const DEFAULT_PLANS: Prisma.PlanCreateInput[] = [
  {
    key: "STARTER",
    name: "Starter",
    description: "Para pequenas equipes organizarem clientes, vendas e tarefas.",
    priceMonthlyCents: 14900,
    priceYearlyCents: 149000,
    trialDays: 14,
    maxUsers: 3,
    maxStorageMb: 1024,
    maxAutomations: 3,
    maxAiRequestsMonth: 200,
    maxApiKeys: 0,
    maxWebhooks: 0,
    features: ["ai_assistant", "automations"],
    highlights: ["Até 3 usuários", "CRM, pipeline e projetos", "Córtex AI (200 req/mês)", "3 automações", "1 GB de documentos"],
    sortOrder: 1,
  },
  {
    key: "PROFESSIONAL",
    name: "Professional",
    description: "Para empresas em crescimento que querem inteligência comercial e operacional.",
    priceMonthlyCents: 39900,
    priceYearlyCents: 399000,
    trialDays: 14,
    maxUsers: 10,
    maxStorageMb: 10240,
    maxAutomations: 20,
    maxAiRequestsMonth: 1500,
    maxApiKeys: 0,
    maxWebhooks: 3,
    features: ["ai_assistant", "automations", "playbooks", "webhooks", "executive_report", "xlsx_export", "client_portal"],
    highlights: ["Até 10 usuários", "Playbooks e 20 automações", "Relatório Executivo em PDF", "Portal do Cliente", "Webhooks"],
    sortOrder: 2,
  },
  {
    key: "BUSINESS",
    name: "Business",
    description: "Para operações maiores com integrações, API e governança.",
    priceMonthlyCents: 99000,
    priceYearlyCents: 990000,
    trialDays: 14,
    maxUsers: 30,
    maxStorageMb: 51200,
    maxAutomations: 100,
    maxAiRequestsMonth: 6000,
    maxApiKeys: 10,
    maxWebhooks: 20,
    features: [
      "ai_assistant", "automations", "playbooks", "webhooks", "api_access", "executive_report",
      "xlsx_export", "client_portal", "custom_roles", "integrations", "audit_log",
    ],
    highlights: ["Até 30 usuários", "API pública e API keys", "Papéis personalizados", "Log de auditoria", "6.000 req. de IA/mês"],
    sortOrder: 3,
  },
  {
    key: "ENTERPRISE",
    name: "Enterprise",
    description: "Contrato personalizado, limites sob medida e suporte dedicado.",
    priceMonthlyCents: null,
    priceYearlyCents: null,
    trialDays: 14,
    maxUsers: null,
    maxStorageMb: null,
    maxAutomations: null,
    maxAiRequestsMonth: null,
    maxApiKeys: null,
    maxWebhooks: null,
    features: [
      "ai_assistant", "automations", "playbooks", "webhooks", "api_access", "executive_report",
      "xlsx_export", "client_portal", "custom_roles", "integrations", "audit_log",
    ],
    highlights: ["Usuários e limites sob medida", "SLA e suporte dedicado", "Onboarding assistido", "Contrato personalizado"],
    sortOrder: 4,
  },
];
